CodeFirstAssignment/CodeFirstAssignment/Models/Vehicle.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web;

namespace CodeFirstAssignment.Models
{
    public class Vehicle
    {
        public int VehicleId { get; set; }
        [Required(ErrorMessage = "Please enter name"), MaxLength(30)]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter color"), MaxLength(30)]
        public string Color { get; set; }
        [Required(ErrorMessage = "Please enter price")]
        public int Price { get; set; }

        [DisplayName("Upload File")]
        public string ImagePath { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }
    }
}

CodeFirstAssignment/CodeFirstAssignment/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CodeFirstAssignment.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CodeFirstAssignment/CodeFirstAssignment/Controllers/VehiclesController.cs
using System;
using System.Data;
using System.Net;
using System.Web.Mvc;
using CodeFirstAssignment.DAL;
using CodeFirstAssignment.Manager;
using CodeFirstAssignment.Models;

namespace CodeFirstAssignment.Controllers
{
    public class VehiclesController : Controller
    {
        private VehicleContext db = new VehicleContext();
        IVehicleManager iVehicle;
        public VehiclesController(IVehicleManager ivehicle)
        {
            iVehicle = ivehicle;
        }

        /// <summary>
        /// display the index
        /// </summary>
        /// <returns></returns>
        // GET: Vehicles
        public ActionResult Index()
        {
            var vehicles = iVehicle.GetAll();
            return View(vehicles);
        }

        /// <summary>
        /// Details Of vehicle
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Vehicles/Details/1
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Vehicle vehicle = iVehicle.GetById(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        /// <summary>
        /// Creating new vehicle get request
        /// </summary>
        /// <returns></returns>
        // GET: Vehicles/Create
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// creating new Vehicle post request
        /// </summary>
        /// <param name="vehicle"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Vehicle vehicle)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    iVehicle.Create(vehicle);
                    return RedirectToAction("Index");
                }
            }
            catch(Exception)
            {
                ModelState.AddModelError(string.Empty, "Unable to save changes. Try again, and if the problem persists contact your system administrator.");
            }
            return View(vehicle);
        }

        /// <summary>
        /// Editing the vehicle get request
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Vehicles/Edit/1
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = iVehicle.GetById(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

      /// <summary>
      /// Editing the vehicle post request
      /// </summary>
      /// <param name="vehicle"></param>
      /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Vehicle vehicle)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    iVehicle.Edit(vehicle);
                    return RedirectToAction("Index");
                }
            }
            catch(Exception)
            {
                ModelState.AddModelError(string.Empty, "Unable to save changes. Try again, and if the problem persists contact your system administrator.");
            }
            return View(vehicle);
        }

        /// <summary>
        /// Searching the Vehicle
        /// </summary>
        /// <param name="vehicle"></param>
        /// <returns></returns>
        public ActionResult Search(Vehicle vehicle)
        {
            var vehicles=db.Vehicles;
            foreach (Vehicle item in vehicles)
            {
                if(item.VehicleId==vehicle.VehicleId)
                {
                    return View("Edit", item);
                }
               }
            ViewBag.result = "does not exist";
            return View("Edit");
        }

        /// <summary>
        /// Deleting the Vehicle Get Request
        /// </summary>
        /// <param name="id"></param>
        /// <param name="saveChangesError"></param>
        /// <returns></returns>
        // GET: Vehicles/Delete/1
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = iVehicle.GetById(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        /// <summary>
        /// Deleting the vehicle post request
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // POST: Vehicles/Delete/1
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                iVehicle.Delete(id);
            }
            catch(Exception)
            {
                return RedirectToAction("Delete");
            }
            return RedirectToAction("Index");
        }
    
    }
}

CodeFirstAssignment/CodeFirstAssignment/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CodeFirstAssignment/CodeFirstAssignment/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CodeFirstAssignment/CodeFirstAssignment/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

CodeFirstAssignment/CodeFirstAssignment/Views/Vehicles/Create.cshtml
@model CodeFirstAssignment.Models.Vehicle

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Vehicles",FormMethod.Post,new {enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vehicle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
            <input type="file" name="ImageFile" required>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>  
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CodeFirstAssignment/CodeFirstAssignment/Views/Vehicles/Delete.cshtml
@model CodeFirstAssignment.Models.Vehicle

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vehicle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CodeFirstAssignment/CodeFirstAssignment/Views/Vehicles/Details.cshtml
@model CodeFirstAssignment.Models.Vehicle

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Vehicle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
           
        </dt>

        <dd>
           <img src="@Url.Content(Model.ImagePath)" width="250" height="250"/>
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.VehicleId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CodeFirstAssignment/CodeFirstAssignment/Views/Vehicles/Edit.cshtml
@model CodeFirstAssignment.Models.Vehicle

@{
    ViewBag.Title = "Edit";
}

<h2>Search and Edit</h2>
@using (Html.BeginForm("Search", "Vehicles"))
{
    <div class="form-group">
        @Html.LabelFor(m=>m.VehicleId)
        @Html.TextBoxFor(m=>m.VehicleId,new { @class="form-control"})
        </div>

        <input type="submit" value="SEARCH"/>
      }


        @using (Html.BeginForm("Edit", "Vehicles"))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Vehicle</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.VehicleId)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }


        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

CodeFirstAssignment/CodeFirstAssignment/Views/Vehicles/Index.cshtml
@model IEnumerable<CodeFirstAssignment.Models.Vehicle>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImagePath)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            <img src="@Url.Content("ImagePath")" width="100" height="100" />
        </td>
        <td>
            @Html.ActionLink("Edit|Search", "Edit", new { id=item.VehicleId }) |
            @Html.ActionLink("Details", "Details", new { id=item.VehicleId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.VehicleId })
        </td>
    </tr>
}

</table>